language: csharp
mono: none
dotnet: 2.0.0
solution: UnityExtras.Converters.sln

install:
  - dotnet tool install coveralls.net --version 1.0.0 --tool-path tools
script:
  - dotnet test UnityExtras.Converters.Tests
  - .\tools\csmacnz.Coveralls --opencover -i coverage.xml --useRelativePaths
